//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetRequest()
        {
            this.AssetRequestApprovalHistory = new HashSet<AssetRequestApprovalHistory>();
            this.Quotation = new HashSet<Quotation>();
        }
    
        public int ID { get; set; }
        public int RequestedBy { get; set; }
        public int RequestedTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int AssetRequestStatusID { get; set; }
        public int Priority { get; set; }
        public string RequestedAsset { get; set; }
    
        public virtual AssetRequestStatus AssetRequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetRequestApprovalHistory> AssetRequestApprovalHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotation { get; set; }
    }
}
