//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRequestApprovalHistory
    {
        public int ID { get; set; }
        public int AssetRequestID { get; set; }
        public int RequestID { get; set; }
        public int ApproverID { get; set; }
        public string Comments { get; set; }
        public int ApprovalStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string RequestedAsset { get; set; }
    
        public virtual AssetRequest AssetRequest { get; set; }
        public virtual AssetRequestStatus AssetRequestStatus { get; set; }
    }
}
