//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assets()
        {
            this.AssetPurchaseOrderMapping = new HashSet<AssetPurchaseOrderMapping>();
            this.ComponentAssetMapping = new HashSet<ComponentAssetMapping>();
            this.ComponentAssetMapping1 = new HashSet<ComponentAssetMapping>();
            this.EmployeeAssetMapping = new HashSet<EmployeeAssetMapping>();
            this.AssetTracker = new HashSet<AssetTracker>();
            this.HardwareAssets = new HashSet<HardwareAssets>();
            this.SoftwareAssets = new HashSet<SoftwareAssets>();
        }
    
        public int ID { get; set; }
        public int AssetTypeID { get; set; }
        public string AssetName { get; set; }
        public string SerialNumber { get; set; }
        public int AssetStatusID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetPurchaseOrderMapping> AssetPurchaseOrderMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentAssetMapping> ComponentAssetMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentAssetMapping> ComponentAssetMapping1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssetMapping> EmployeeAssetMapping { get; set; }
        public virtual AssetTypes AssetTypes { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTracker> AssetTracker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HardwareAssets> HardwareAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareAssets> SoftwareAssets { get; set; }
        public virtual AssetStatus AssetStatus { get; set; }
    }
}
