//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPurchaseOrderMapping
    {
        public int ID { get; set; }
        public int AssetID { get; set; }
        public int PurchaseOrderID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
