//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentAssetMapping
    {
        public int ID { get; set; }
        public int ComponentID { get; set; }
        public Nullable<int> AssignedAssetID { get; set; }
        public Nullable<int> ActualAssetID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ComponentStatusId { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<int> ComponentTypeID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Assets Assets1 { get; set; }
        public virtual Components Components { get; set; }
        public virtual ComponentStatus ComponentStatus { get; set; }
        public virtual ComponentType ComponentType { get; set; }
    }
}
