//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareAssets
    {
        public int ID { get; set; }
        public int AssetID { get; set; }
        public string Model { get; set; }
        public string ServiceTag { get; set; }
        public string Manufacturer { get; set; }
        public System.DateTime WarrantyStartDate { get; set; }
        public System.DateTime WarrantyEndDate { get; set; }
        public string Comment { get; set; }
    
        public virtual Assets Assets { get; set; }
    }
}
