//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.AssetPurchaseOrderMapping = new HashSet<AssetPurchaseOrderMapping>();
        }
    
        public int ID { get; set; }
        public int QuotationID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceFilePath { get; set; }
        public int PurchaseStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetPurchaseOrderMapping> AssetPurchaseOrderMapping { get; set; }
        public virtual PurchaseStatus PurchaseStatus { get; set; }
        public virtual Quotation Quotation { get; set; }
    }
}
